version: '3.8'

services:
  bearer-mcp:
    image: bearer-mcp:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/workspace
      - ./config:/config
    ports:
      - "8000:8000"
    environment:
      - MCP_WORKING_DIRECTORY=/workspace
      - MCP_TRANSPORT=sse
      - MCP_SSE_HOST=0.0.0.0
      - MCP_SSE_PORT=8000
      - PYTHONUNBUFFERED=1
    command: python bearer_mcp_main.py
    stdin_open: true
    tty: true
    
  # Alternative: with Bearer CLI pre-installed
  bearer-mcp-with-cli:
    image: bearer-mcp:final
    volumes:
      - ./workspace:/workspace
      - ./config:/config
      - /usr/local/bin/bearer:/usr/local/bin/bearer:ro  # Mount Bearer from host
    environment:
      - MCP_WORKING_DIRECTORY=/workspace
      - PYTHONUNBUFFERED=1
    command: python bearer_mcp_main.py
    stdin_open: true
    tty: true