name: Security Scanning

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install and run Safety check
        run: |
          python -m pip install --upgrade pip
          pip install safety
          
          # Run safety check and continue on error
          echo "=== Checking for known vulnerabilities ==="
          safety check --continue-on-error || true

  bearer-scan:
    name: Bearer Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bearer CLI
        run: |
          BEARER_VERSION=$(curl -s https://api.github.com/repos/Bearer/bearer/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          echo "Installing Bearer v${BEARER_VERSION}"
          curl -L -o /tmp/bearer.tar.gz \
            "https://github.com/Bearer/bearer/releases/download/v${BEARER_VERSION}/bearer_${BEARER_VERSION}_linux_amd64.tar.gz"
          sudo tar -xzf /tmp/bearer.tar.gz -C /usr/local/bin/
          sudo chmod +x /usr/local/bin/bearer
          bearer version

      - name: Run Bearer Security Scan
        run: |
          bearer scan . \
            --severity high,critical \
            --quiet || true
          
          echo "Bearer scan completed."


  secrets-scan:
    name: Secret Detection
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [dependency-check, bearer-scan, secrets-scan]
    if: always()
    
    steps:
      - name: Security Scan Summary
        run: |
          echo "=== Security Scan Results Summary ==="
          echo "Dependency Check: ${{ needs.dependency-check.result }}"
          echo "Bearer Scan: ${{ needs.bearer-scan.result }}"
          echo "Secret Detection: ${{ needs.secrets-scan.result }}"
          echo ""
          
          if [ "${{ needs.dependency-check.result }}" = "success" ] && \
             [ "${{ needs.bearer-scan.result }}" = "success" ] && \
             [ "${{ needs.secrets-scan.result }}" = "success" ]; then
            echo "✓ All security scans completed successfully!"
          else
            echo "⚠ Some security scans had issues - review logs above"
          fi